//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Organicart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class billing
    {
        public int id { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> address_id { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> store_id { get; set; }
    
        public virtual client client { get; set; }
        public virtual product product { get; set; }
        public virtual store store { get; set; }
    }
}
