//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Organicart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class billing
    {
        public int id { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> address_id { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> store_id { get; set; }
    
        public virtual client client { get; set; }
        public virtual product product { get; set; }
        public virtual store store { get; set; }
    }
}
