//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Organicart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        public client()
        {
            this.billings = new HashSet<billing>();
            this.client_address = new HashSet<client_address>();
        }
    
        public int id { get; set; }
        public int user_id { get; set; }
        public string dui { get; set; }
        public string name { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public Nullable<int> phone { get; set; }
        public byte[] photo { get; set; }
    
        public virtual ICollection<billing> billings { get; set; }
        public virtual ICollection<client_address> client_address { get; set; }
        public virtual user user { get; set; }
    }
}
