//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Organicart.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OrganicartEntities : DbContext
    {
        public OrganicartEntities()
            : base("name=OrganicartEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<billing> billings { get; set; }
        public DbSet<category> categories { get; set; }
        public DbSet<client> clients { get; set; }
        public DbSet<client_address> client_address { get; set; }
        public DbSet<product> products { get; set; }
        public DbSet<store> stores { get; set; }
        public DbSet<user> users { get; set; }
    }
}
