//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Organicart.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OrganicartEntities : DbContext
    {
        public OrganicartEntities()
            : base("name=OrganicartEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<billing> billings { get; set; }
        public DbSet<category> categories { get; set; }
        public DbSet<client> clients { get; set; }
        public DbSet<client_address> client_address { get; set; }
        public DbSet<product> products { get; set; }
        public DbSet<store> stores { get; set; }
        public DbSet<user> users { get; set; }
    }
}
