//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Organicart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public product()
        {
            this.billings = new HashSet<billing>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public byte[] photo { get; set; }
        public Nullable<int> category_id { get; set; }
        public Nullable<double> price { get; set; }
        public int stock { get; set; }
    
        public virtual ICollection<billing> billings { get; set; }
        public virtual category category { get; set; }
    }
}
