//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Organicart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public product()
        {
            this.billings = new HashSet<billing>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public byte[] photo { get; set; }
        public Nullable<int> category_id { get; set; }
        public Nullable<double> price { get; set; }
        public int stock { get; set; }
    
        public virtual ICollection<billing> billings { get; set; }
        public virtual category category { get; set; }
    }
}
