//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Organicart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class store
    {
        public store()
        {
            this.billings = new HashSet<billing>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string store_address { get; set; }
    
        public virtual ICollection<billing> billings { get; set; }
    }
}
