//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Organicart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class store
    {
        public store()
        {
            this.billings = new HashSet<billing>();
            this.inventories = new HashSet<inventory>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string store_address { get; set; }
    
        public virtual ICollection<billing> billings { get; set; }
        public virtual ICollection<inventory> inventories { get; set; }
    }
}
