//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Organicart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.clients = new HashSet<client>();
        }
    
        public int id { get; set; }
        public string username { get; set; }
        public int role_id { get; set; }
        public string password { get; set; }
    
        public virtual ICollection<client> clients { get; set; }
    }
}
