//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Organicart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.clients = new HashSet<client>();
        }
    
        public int id { get; set; }
        public string username { get; set; }
        public int role_id { get; set; }
        public string password { get; set; }
    
        public virtual ICollection<client> clients { get; set; }
    }
}
